In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ipywidgets import interact, fixed
import tkinter as tk
from tkinter import ttk
from tkinter.ttk import *

df = pd.read_csv('recomendacion.csv', index_col=0)

df

,Te gusta la pizza,Te gusta la pasta,Te gusta la hamburguesa,Te gusta la carne,Te gusta el pollo
Usuario,,,,,
Juan,5,4,2,3,5
Ana,3,5,4,2,4
Luis,4,3,3,4,2
Maria,2,2,5,5,1
Diego,5,4,4,3,3
Carla,3,5,2,5,4
Andres,4,3,5,2,5
Sofia,5,2,4,5,3

In [ ]:
root=tk.Tk()
root.title('Modificación de recomendaciones')

# Crear widget de selección de usuario
user_select = ttk.Combobox(root, values=df.index.values)
user_select.pack(padx=10, pady=10)

# Crear botón de guardar cambios
save_button = tk.Button(root, text='Guardar cambios')
save_button.pack(padx=10, pady=10)

# Crear diccionario para valores iniciales y valores modificados
initial_values = {}
modified_values = {}

# Función para actualizar el diccionario de valores modificados
def update_modified_values():
    user = user_select.get()
    modified_values[user] = {
        'Te gusta la pizza': pizza_slider.get(),
        'Te gusta la pasta': pasta_slider.get(),
        'Te gusta la hamburguesa': hamburguesa_slider.get(),
        'Te gusta la carne': carne_slider.get(),
        'Te gusta el pollo': pollo_slider.get()
    }
    
pizza_slider = tk.Scale(root, from_=0, to=5, resolution=0.01, orient='horizontal')
pasta_slider = tk.Scale(root, from_=0, to=5, resolution=0.01, orient='horizontal')
hamburguesa_slider = tk.Scale(root, from_=0, to=5, resolution=0.01, orient='horizontal')
carne_slider = tk.Scale(root, from_=0, to=5, resolution=0.01, orient='horizontal')
pollo_slider = tk.Scale(root, from_=0, to=5, resolution=0.01, orient='horizontal')

# Empaquetar sliders en la ventana
pizza_slider.pack()
pasta_slider.pack()
hamburguesa_slider.pack()
carne_slider.pack()
pollo_slider.pack()

# Conectar botón de guardar cambios a la función de actualización de valores
save_button.configure(command=update_modified_values)

# Ejecutar bucle principal de la ventana
root.mainloop()